name: check

on:
  pull_request:
    branches:
      - main

concurrency:
  group: check-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: cargo check --workspace --locked
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - run: cargo check --workspace --locked
        env:
          RUSTUP_TOOLCHAIN: 1.88.0
